api_version = "2024-01"

[[extensions]]
type = "theme"
name = "Gallery Wall Builder"
handle = "gallery-wall-builder"

[[extensions.targeting]]
module = "./blocks/gallery-block.liquid"
target = "section"
